- name: "Add lines to shell config: {{ description }}"
  blockinfile:
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ description }}"
    create: no
    state: present
    validate: "{{ validate_file }}"
  become: true
  become_user: root

