- name: "Configure common environment vars sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_common_dir_path }}/{{ env_vars_filename }}"
    block_lines: |
      # export all common/global environment vars in this file:

- name: "Configure common interactive aliases/functions sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_common_dir_path }}/{{ aliases_filename }}"
    block_lines: |
      # put all common interactive aliases/functions in this file:

- name: "Configure common logout actions sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_common_dir_path }}/{{ logout_actions_filename }}"
    block_lines: |
      # put all common logout actions in this file:

- name: "Configure common $ENV, $BASH_ENV var sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_common_dir_path }}/{{ std_env_filename }}"
    block_lines: |
      # set $ENV to load aliases for interactive system shell:
      export ENV="{{ shell_common_dir_path }}/{{ aliases_filename }}"
      # set $BASH_ENV to load aliases for non-interactive bash shell:
      export BASH_ENV="{{ bash_specific_dir_path }}/{{ std_env_filename }}"

