- name: "Configure {{ shell_name }} environment vars sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_specific_dir_path }}/{{ env_vars_filename }}"
    block_lines: |
      # source common environment vars:
      . "{{ shell_common_dir_path }}/{{ env_vars_filename }}"
      # append {{ shell_name }}-specific env var exports below this ansible-managed block.

- name: "Configure {{ shell_name }} interactive aliases/functions/behavior sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_specific_dir_path }}/{{ interactive_filename }}"
    block_lines: |
      # source common interactive aliases/functions/behavior:
      . "{{ shell_common_dir_path }}/{{ interactive_filename }}"
      # append {{ shell_name }}-specific aliases/functions/behavior below this ansible-managed block.

- name: "Configure {{ shell_name }} logout actions sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_specific_dir_path }}/{{ logout_actions_filename }}"
    block_lines: |
      # source common logout actions:
      . "{{ shell_common_dir_path }}/{{ logout_actions_filename }}"
      # append {{ shell_name }}-specific logout actions below this ansible-managed block.

- name: "Configure {{ shell_name }} $ENV, $BASH_ENV var sourcing"
  include_tasks: add_core_file.yml
  vars:
    filepath: "{{ shell_specific_dir_path }}/{{ std_env_filename }}"
    block_lines: |
      # source common $ENV, $BASH_ENV configuration:
      . "{{ shell_common_dir_path }}/{{ std_env_filename }}"

