- name: "Configure new shell-common files to source"
  include_tasks: config_common.yml

- name: "Configure new shell-specific files to source"
  include_tasks: config_shell_specific.yml
  vars:
    shell_name: "{{ item[0] }}"
    shell_specific_dir_path: "{{ item[1] }}"
  loop:
    - "{{ ['bash', bash_specific_dir_path] }}"
    - "{{ ['zsh', zsh_specific_dir_path] }}"
    - "{{ ['ksh', ksh_specific_dir_path] }}"
    - "{{ ['sh', sh_specific_dir_path] }}"

- name: "Configure standard bash files (.bash_profile, .bashrc)"
  include_tasks: config_bash.yml

- name: "Configure standard zsh files (.zshenv, .zshrc)"
  include_tasks: config_zsh.yml

