- name: "Configure new shell-common files to source"
  ansible.builtin.include_tasks: config_common.yml

- name: "Configure new shell-specific files to source"
  ansible.builtin.include_tasks: config_shell_specific.yml
  vars:
    shell_name: "{{ item[0] }}"
    shell_specific_dir_path: "{{ item[1] }}"
  loop:
    - "{{ ['bash', full_bash_specific_dir_path] }}"
    - "{{ ['zsh', full_zsh_specific_dir_path] }}"
    - "{{ ['ksh', full_ksh_specific_dir_path] }}"
    - "{{ ['fish', full_fish_specific_dir_path] }}"
    - "{{ ['sh', full_sh_specific_dir_path] }}"

- name: "Configure standard bash files (.bash_profile, .bashrc, .bash_logout)"
  ansible.builtin.include_tasks: config_bash.yml

- name: "Configure standard zsh files (.zshenv, .zshrc, .zlogout)"
  ansible.builtin.include_tasks: config_zsh.yml

- name: "Configure standard ksh files (.kshrc)"
  ansible.builtin.include_tasks: config_ksh.yml

- name: "Configure standard fish files (.config/fish/config.fish)"
  ansible.builtin.include_tasks: config_fish.yml

- name: "Configure standard sh files (.profile)"
  ansible.builtin.include_tasks: config_sh.yml

